export interface BrandingConfig {
  companyName: string
  logoUrl: string | null
  primaryColor: string
  accentColor: string
  reportFooterText: string
  reportHeaderText: string
  hidePoweredBySpotbot: boolean
  hideSpotbotLogo: boolean
}

export const DEFAULT_BRANDING: BrandingConfig = {
  companyName: 'Spotbot',
  logoUrl: null,
  primaryColor: '#6366f1',
  accentColor: '#8b5cf6',
  reportFooterText:
    'Generated by Spotbot · spotbot.io · ' +
    'This report reflects publicly available data.',
  reportHeaderText: 'Fraud Analysis Report',
  hidePoweredBySpotbot: false,
  hideSpotbotLogo: false,
}
