// import React from 'react';
// import { renderToStream, Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer';
// import { S3Client } from '@aws-sdk/client-s3';
// import { Upload } from '@aws-sdk/lib-storage';
// import { env } from '../config/env.js';

// const s3 = new S3Client({
//   region: env.S3_REGION,
//   endpoint: env.S3_ENDPOINT,
//   credentials: {
//     accessKeyId: env.S3_ACCESS_KEY,
//     secretAccessKey: env.S3_SECRET_KEY,
//   },
// });

// const styles = StyleSheet.create({
//   page: { backgroundColor: '#0f172a', color: '#ffffff', padding: 40, fontFamily: 'Helvetica' },
//   title: { fontSize: 32, fontWeight: 'bold', marginBottom: 10 },
//   subtitle: { fontSize: 20, marginBottom: 20 },
//   section: { margin: 10, padding: 10 },
//   row: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 10 },
//   text: { fontSize: 12, marginBottom: 5 },
//   scoreGreen: { color: '#4ade80' },
//   scoreAmber: { color: '#fbbf24' },
//   scoreRed: { color: '#f87171' },
// });

// const PdfDocument = ({ scan }: { scan: any }) => {
//   const dateStr = new Date(scan.createdAt).toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' });
  
//   let scoreColor = styles.scoreGreen;
//   if (scan.riskLevel === 'medium') scoreColor = styles.scoreAmber;
//   if (scan.riskLevel === 'high') scoreColor = styles.scoreRed;

//   return React.createElement(Document, null,
//     React.createElement(Page, { size: 'A4', style: styles.page },
//       React.createElement(View, { style: styles.section },
//         React.createElement(Text, { style: styles.title }, 'SPOTBOT'),
//         React.createElement(Text, { style: styles.subtitle }, 'Fraud Analysis Report'),
//         React.createElement(Text, { style: styles.text }, `Influencer handle: @${scan.handle}`),
//         React.createElement(Text, { style: styles.text }, `Platform: ${scan.platform}`),
//         React.createElement(Text, { style: styles.text }, `Scan date: ${dateStr}`),
//         React.createElement(Text, { style: [styles.title, scoreColor, { marginTop: 40 }] }, `Overall Fraud Score: ${scan.fraudScore || 0}`),
//         React.createElement(Text, { style: [styles.subtitle, scoreColor] }, `Risk Level: ${(scan.riskLevel || 'Low').toUpperCase()}`)
//       )
//     ),
//     React.createElement(Page, { size: 'A4', style: styles.page },
//       React.createElement(View, { style: styles.section },
//         React.createElement(Text, { style: styles.title }, 'Executive Summary'),
//         React.createElement(Text, { style: styles.subtitle }, 'Risk Summary'),
//         React.createElement(Text, { style: styles.text }, 'Analysis complete based on multiple signals.'),
//         React.createElement(View, { style: [styles.row, { marginTop: 20 }] },
//           React.createElement(View, null,
//             React.createElement(Text, { style: styles.text }, 'Real Reach'),
//             React.createElement(Text, { style: styles.text }, `${scan.realReach || 0} authentic followers`)
//           ),
//           React.createElement(View, null,
//             React.createElement(Text, { style: styles.text }, 'Data Quality'),
//             React.createElement(Text, { style: styles.text }, 'Full')
//           )
//         )
//       )
//     ),
//     React.createElement(Page, { size: 'A4', style: styles.page },
//       React.createElement(View, { style: styles.section },
//         React.createElement(Text, { style: styles.title }, 'Signal Details'),
//         React.createElement(Text, { style: styles.text }, 'See web dashboard for granular details.')
//       )
//     ),
//     React.createElement(Page, { size: 'A4', style: styles.page },
//       React.createElement(View, { style: [styles.section, { marginTop: 'auto' }] },
//         React.createElement(Text, { style: styles.text }, `Generated by Spotbot on ${dateStr}`),
//         React.createElement(Text, { style: styles.text }, 'This report is based on publicly available data analyzed at the time of scan'),
//         React.createElement(Text, { style: styles.text }, 'spotbot.io')
//       )
//     )
//   );
// };

// export class PdfService {
//   async generatePdf(scan: any): Promise<string> {
//     const stream = await renderToStream(
//       React.createElement(PdfDocument as any, { scan })
//     );
    
//     const key = `reports/${scan.id}.pdf`;

//     const upload = new Upload({
//       client: s3,
//       params: {
//         Bucket: env.S3_BUCKET,
//         Key: key,
//         Body: stream as any,
//         ContentType: 'application/pdf',
//       },
//     });

//     await upload.done();

//     return `${env.S3_ENDPOINT}/${env.S3_BUCKET}/${key}`;
//   }
// }









import React from 'react';
import {
  renderToStream,
  Document,
  Page,
  Text,
  View,
  StyleSheet,
} from '@react-pdf/renderer';

import { S3Client } from '@aws-sdk/client-s3';
import { Upload } from '@aws-sdk/lib-storage';
import { env } from '../config/env.js';

const s3 = new S3Client({
  region: env.S3_REGION,
  endpoint: env.S3_ENDPOINT,
  credentials: {
    accessKeyId: env.S3_ACCESS_KEY,
    secretAccessKey: env.S3_SECRET_KEY,
  },
});

const styles = StyleSheet.create({
  page: {
    backgroundColor: '#0f172a',
    color: '#ffffff',
    padding: 40,
    fontFamily: 'Helvetica',
  },

  title: {
    fontSize: 32,
    fontWeight: 'bold',
    marginBottom: 10,
  },

  subtitle: {
    fontSize: 20,
    marginBottom: 20,
  },

  section: {
    margin: 10,
    padding: 10,
  },

  row: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 10,
  },

  text: {
    fontSize: 12,
    marginBottom: 5,
  },

  scoreGreen: {
    color: '#4ade80',
  },

  scoreAmber: {
    color: '#fbbf24',
  },

  scoreRed: {
    color: '#f87171',
  },
});

function PdfDocument({ scan }: { scan: any }) {
  const dateStr = new Date(scan.createdAt).toLocaleDateString(
    'en-US',
    {
      month: 'long',
      day: 'numeric',
      year: 'numeric',
    }
  );

  let scoreColor = styles.scoreGreen;

  if (scan.riskLevel === 'medium')
    scoreColor = styles.scoreAmber;

  if (scan.riskLevel === 'high')
    scoreColor = styles.scoreRed;

  return React.createElement(
    Document,
    null,

    React.createElement(
      Page,
      { size: 'A4', style: styles.page },

      React.createElement(
        View,
        { style: styles.section },

        React.createElement(
          Text,
          { style: styles.title },
          'SPOTBOT'
        ),

        React.createElement(
          Text,
          { style: styles.subtitle },
          'Fraud Analysis Report'
        ),

        React.createElement(
          Text,
          { style: styles.text },
          `Influencer handle: @${scan.handle}`
        ),

        React.createElement(
          Text,
          { style: styles.text },
          `Platform: ${scan.platform}`
        ),

        React.createElement(
          Text,
          { style: styles.text },
          `Scan date: ${dateStr}`
        ),

        React.createElement(
          Text,
          {
            style: [
              styles.title,
              scoreColor,
              { marginTop: 40 },
            ],
          },
          `Overall Fraud Score: ${scan.fraudScore || 0}`
        ),

        React.createElement(
          Text,
          {
            style: [
              styles.subtitle,
              scoreColor,
            ],
          },
          `Risk Level: ${(scan.riskLevel || 'Low').toUpperCase()}`
        )
      )
    ),

    React.createElement(
      Page,
      { size: 'A4', style: styles.page },

      React.createElement(
        View,
        { style: styles.section },

        React.createElement(
          Text,
          { style: styles.title },
          'Executive Summary'
        ),

        React.createElement(
          Text,
          { style: styles.subtitle },
          'Risk Summary'
        ),

        React.createElement(
          Text,
          { style: styles.text },
          'Analysis complete based on multiple signals.'
        )
      )
    )
  );
}

export class PdfService {

  async generatePdf(scan: any): Promise<string> {

    const stream = await renderToStream(
      PdfDocument({ scan }) as any
    );

    const key = `reports/${scan.id}.pdf`;

    const upload = new Upload({
      client: s3,

      params: {
        Bucket: env.S3_BUCKET,
        Key: key,

        Body: stream as any,

        ContentType: 'application/pdf',
      },
    });

    await upload.done();

    return `${env.S3_ENDPOINT}/${env.S3_BUCKET}/${key}`;
  }
}