import { db } from '../db/client.js'
import { whiteLabel, organizations } from '../db/schema/index.js'
import { eq } from 'drizzle-orm'
import { logger } from '../utils/logger.js'
import { AppError, NotFoundError, ValidationError } from '../middleware/error-handler.js'

// Default Spotbot branding (fallback)
export const DEFAULT_BRANDING = {
  companyName: 'Spotbot',
  logoUrl: null as string | null,
  primaryColor: '#6366f1',   // indigo
  accentColor: '#8b5cf6',    // violet
  reportFooterText:
    'Generated by Spotbot · spotbot.io · ' +
    'This report reflects publicly available data.',
  reportHeaderText: 'Fraud Analysis Report',
  hidePoweredBySpotbot: false,
  hideSpotbotLogo: false,
}

export type BrandingConfig = typeof DEFAULT_BRANDING

export class WhiteLabelService {

  // Check if org has enterprise plan
  private async requireEnterprise(orgId: string): Promise<void> {
    const org = await db.query.organizations.findFirst({
      where: eq(organizations.id, orgId),
      columns: { plan: true },
    })

    if (!org) throw new NotFoundError('Organization')

    if (org.plan !== 'enterprise') {
      throw new AppError(
        402,
        'ENTERPRISE_REQUIRED',
        'White label reports require an Enterprise plan. ' +
        'Contact sales@spotbot.io to upgrade.',
      )
    }
  }

  // Get branding config for an org
  // Returns default Spotbot branding if no white label set
  async getBranding(orgId: string): Promise<BrandingConfig> {
    const settings = await db.query.whiteLabel.findFirst({
      where: eq(whiteLabel.organizationId, orgId),
    })

    if (!settings) return DEFAULT_BRANDING

    return {
      companyName: settings.companyName ?? DEFAULT_BRANDING.companyName,
      logoUrl: settings.logoUrl ?? null,
      primaryColor:
        settings.primaryColor ?? DEFAULT_BRANDING.primaryColor,
      accentColor:
        settings.accentColor ?? DEFAULT_BRANDING.accentColor,
      reportFooterText:
        settings.reportFooterText ?? DEFAULT_BRANDING.reportFooterText,
      reportHeaderText:
        settings.reportHeaderText ?? DEFAULT_BRANDING.reportHeaderText,
      hidePoweredBySpotbot: settings.hidePoweredBySpotbot,
      hideSpotbotLogo: settings.hideSpotbotLogo,
    }
  }

  // Update branding settings (enterprise only)
  async updateBranding(
    orgId: string,
    updates: {
      companyName?: string
      logoUrl?: string
      primaryColor?: string
      accentColor?: string
      reportFooterText?: string
      reportHeaderText?: string
      hidePoweredBySpotbot?: boolean
      hideSpotbotLogo?: boolean
    },
  ): Promise<BrandingConfig> {
    await this.requireEnterprise(orgId)

    // Validate hex colors if provided
    if (updates.primaryColor && !/^#[0-9A-Fa-f]{6}$/.test(
      updates.primaryColor
    )) {
      throw new ValidationError(
        'primaryColor must be a valid hex color (e.g. #6366f1)'
      )
    }

    if (updates.accentColor && !/^#[0-9A-Fa-f]{6}$/.test(
      updates.accentColor
    )) {
      throw new ValidationError(
        'accentColor must be a valid hex color'
      )
    }

    // Upsert white label settings
    await db
      .insert(whiteLabel)
      .values({
        organizationId: orgId,
        ...updates,
      })
      .onConflictDoUpdate({
        target: whiteLabel.organizationId,
        set: {
          ...updates,
          updatedAt: new Date(),
        },
      })

    logger.info({ orgId }, 'White label branding updated')

    return this.getBranding(orgId)
  }

  // Reset branding to Spotbot defaults
  async resetBranding(orgId: string): Promise<void> {
    await this.requireEnterprise(orgId)

    await db
      .delete(whiteLabel)
      .where(eq(whiteLabel.organizationId, orgId))

    logger.info({ orgId }, 'White label branding reset to defaults')
  }

  // Upload logo (stores URL after upload to Supabase/S3)
  async updateLogoUrl(
    orgId: string,
    logoUrl: string,
  ): Promise<void> {
    await this.requireEnterprise(orgId)

    await db
      .insert(whiteLabel)
      .values({
        organizationId: orgId,
        logoUrl,
      })
      .onConflictDoUpdate({
        target: whiteLabel.organizationId,
        set: { logoUrl, updatedAt: new Date() },
      })
  }
}

export const whiteLabelService = new WhiteLabelService()
